

### Tarefa 01

In [102]:
import numpy as np
import pandas as pd

In [164]:
gabarito=[['matematica',24],['portugues',18],['geografia',8],['ingles',8],['historia',8],['fisica',12],['quimica',12]]
gabarito=pd.DataFrame(gabarito,columns=['disciplina','n_questoes'])
gabarito

   disciplina  n_questoes
0  matematica          24
1   portugues          18
2   geografia           8
3      ingles           8
4    historia           8
5      fisica          12
6     quimica          12

In [163]:
gabarito['pontos'].sum()

90

In [186]:
np.random.seed(42)
df_mat = pd.DataFrame(np.random.randint(24, size=(100, 1)), columns=['Qt_acertos'])

df_por = pd.DataFrame(np.random.randint(18, size=(100, 1)), columns=['Qt_acertos'])

df_geo = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_ing = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_his = pd.DataFrame(np.random.randint(8, size=(100, 1)), columns=['Qt_acertos'])

df_fis = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])

df_qui = pd.DataFrame(np.random.randint(12, size=(100, 1)), columns=['Qt_acertos'])
df_qui_perc=(df_qui/12)*100
df_fis_perc=(df_fis/12)*100
df_his_perc=(df_his/8)*100
df_ing_perc=(df_ing/8)*100
df_geo_perc=(df_geo/8)*100
df_por_perc=(df_por/18)*100
df_mat_perc=(df_mat/24)*100

df_qui_perc

    Qt_acertos
0    25.000000
1    66.666667
2    33.333333
3    66.666667
4    25.000000
..         ...
95   25.000000
96   25.000000
97   41.666667
98   91.666667
99   16.666667

[100 rows x 1 columns]

In [188]:
total=df_qui+df_fis+df_his+df_ing+df_geo+df_por+df_mat
total/90

    Qt_acertos
0     0.388889
1     0.533333
2     0.555556
3     0.355556
4     0.333333
..         ...
95    0.377778
96    0.300000
97    0.444444
98    0.444444
99    0.466667

[100 rows x 1 columns]

In [213]:
aprovados=total[total>45]
aprovados.dropna(inplace=True)
aprovados.shape

(31, 1)


### Tarefa 02

In [220]:
df_eliminados = total[(df_mat['Qt_acertos'] == 0) | 
                      (df_fis['Qt_acertos'] == 0) | 
                      (df_qui['Qt_acertos'] == 0)]

df_eliminados.head()

    Qt_acertos
3           32
6           29
10          31
12          42
14          31

### Tarefa 03

In [236]:
import pandas as pd

In [238]:
#Segunda questão
base = pd.read_csv('/content/registros de vacinacao covid ACRE.csv', sep=';')
base

,document_id,paciente_id,paciente_idade,paciente_datanascimento,paciente_enumsexobiologico,paciente_racacor_codigo,paciente_racacor_valor,paciente_endereco_coibgemunicipio,paciente_endereco_copais,paciente_endereco_nmmunicipio,...,vacina_lote,vacina_fabricante_nome,vacina_fabricante_referencia,vacina_dataaplicacao,vacina_descricao_dose,vacina_codigo,vacina_nome,sistema_origem,data_importacao_rnds,id_sistema_origem
0,b19cd280-474c-4c22-a35d-8c06bc04a4e0-i0b0,2e091c9a37d3f50d1d705fc80c6448c6fc69b44da9e936...,69,1951-12-28,F,3,PARDA,120050.0,10.0,SENA MADUREIRA,...,210052A,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-23,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-25T03:27:19.000Z,NaN
1,a1acc0b6-1cf6-4c4b-adcb-06b473a0faaf-i0b0,f4e17a9e5354cb45e223d85eda02fb2f76048c801675f5...,81,1939-11-22,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,210110,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-29,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-30T16:03:14.000Z,NaN
2,af279a98-ba1f-47ea-8214-314a98040b0d-i0b0,6734b26bccf826130ebffa66575977bbe71477b12bcf42...,69,1951-08-14,M,4,AMARELA,120020.0,10.0,CRUZEIRO DO SUL,...,210135,FUNDACAO BUTANTAN,Organization/61189445000156,2021-04-16,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-04-16T15:54:39.000Z,NaN
3,4879308e-5050-46bb-b8e2-11fa5646a05c-i0b0,84a341fd350c1ba7117fccbb4d2df417bc0fac0fffac37...,51,1969-12-15,F,3,PARDA,120040.0,10.0,RIO BRANCO,...,202010040,FUNDACAO BUTANTAN,Organization/61189445000156,2021-02-19,2ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-10T14:40:54.000Z,NaN
4,000e911b-e3a4-4114-a735-d1f2e6e3797f-i0b0,c59571e19f368d4b0cf08cd3bcabb32e5cd8baad5340f6...,65,1955-11-21,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-29,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T19:44:28.000Z,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169066,1d8f6ea9-d3f5-4882-9fe4-9d2f3ef88d77-i0b0,8048cb43bf62574837987f9351325ab06d3bc3884ee2f7...,25,1995-02-05,F,5,INDIGENA,120035.0,10.0,MARECHAL THAUMATURGO,...,202010028,FUNDACAO BUTANTAN,Organization/61189445000156,2021-01-26,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-02-03T19:13:58.000Z,NaN
169067,77ff98a4-79fb-47c9-aafa-8bf45708c4bc-i0b0,0548218b49585839b8f83c202bccac61f6a9c48cc1ea94...,68,1953-02-03,M,4,AMARELA,120040.0,10.0,RIO BRANCO,...,212VCD001ZVB,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-03-25,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-04-03T21:20:19.000Z,NaN
169068,1da067bc-9989-4fa4-8838-e1e40cdfeebf-i0b0,de5f1131ff4f954cfb28ebdcb964b6e25e83620ce9df49...,65,1955-06-05,M,2,PRETA,120017.0,10.0,CAPIXABA,...,210077,FUNDACAO BUTANTAN,Organization/61189445000156,2021-03-30,1ª Dose,86,Covid-19-Coronavac-Sinovac/Butantan,Novo PNI,2021-03-31T20:38:55.000Z,NaN
169069,eacc22e0-6f78-460f-a8e7-d85c6129951e-i0b0,fd1fb8d6e5de6eceeb7bb8246243d3c5cf85cdca01d849...,76,1944-06-15,F,1,BRANCA,120040.0,10.0,RIO BRANCO,...,4120Z025,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-26,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-02-27T23:41:11.000Z,NaN
169070,02795bd0-b1a7-49c1-83ca-90a9f9b4b794-i0b0,a22dbf631ad78dc6961100cbd6ec5f12ee80cd25148d84...,81,1939-08-08,M,3,PARDA,120040.0,10.0,RIO BRANCO,...,4120Z025,FUNDACAO OSWALDO CRUZ,Organization/33781055000135,2021-02-27,1ª Dose,85,Vacina Covid-19 - Covishield,Novo PNI,2021-03-15T14:27:07.000Z,NaN

In [245]:
#1. Quantas vacinas estão registradas nessa base?  
print(f'Essa base de dados possue: {base.shape}')

Essa base de dados possue: (169071, 34)

In [281]:
#2. Quantos pacientes foram vacinados? (considere um paciente para cada valor único de ```paciente_id```)  
base['paciente_id'].nunique()

120517

In [280]:
#3. Quantos pacientes únicos tomaram a primeira dose? OBS: Há um caractere especial neste campo. 
primeira_dose=base[base['vacina_descricao_dose']=='\xa0\xa0\xa0\xa01ª\xa0Dose']
primeira_dose.shape

(120939, 34)

In [285]:
#4. Quantos pacientes com menos de 18 anos foram vacinados?  
paciente_menos_18=base[base['paciente_idade']<18]
paciente_menos_18.nunique().shape

(34,)

In [277]:
#5. Quantos estabelecimentos aplicaram vacina no Acre?
base['estalecimento_nofantasia'].unique().shape

(103,)

### Tarefa 04

In [305]:
estabelecimento=paciente_menos_18['estalecimento_nofantasia'].value_counts()
df_local=pd.DataFrame(estabelecimento)
df_local.reset_index(inplace=True)
df_local.columns=['estabelecimento','qtd_aplicada']
df_local.head()

                                     estabelecimento  qtd_aplicada
0                  POLO BASE DE MARECHAL THAUMATURGO             9
1                      UBS VICENTE VARELA DE ALMEIDA             8
2                                 POLO BASE DE FEIJO             6
3  DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...             4
4                                 POLO BASE INDIGENA             4

In [306]:
#1. crie uma cópia do *DataFrame* original, contendo somente os registros de vacinas realizadas a menores de 18 anos.  
df_local.copy()

                                      estabelecimento  qtd_aplicada
0                   POLO BASE DE MARECHAL THAUMATURGO             9
1                       UBS VICENTE VARELA DE ALMEIDA             8
2                                  POLO BASE DE FEIJO             6
3   DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...             4
4                                  POLO BASE INDIGENA             4
5                           POLO BASE DE ASSIS BRASIL             3
6    SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL             3
7                   CENTRO DE SAUDE DIAMANTINO MACEDO             3
8                            POLO BASE DE MANCIO LIMA             3
9                           POLO BASE DE PORTO WALTER             2
10  UNIDADE ASSISTENCIAL A SAUDE INDIGENA DE TARAU...             2
11                     POLO INDIGENA DE MANOEL URBANO             2
12    DISTRITO SANITARIO ESPECIAL INDIGENA ALTO PURUS             1
13    UNIDADE DE SAUDE DA FAMILIA ALVARO ARAUJO NOBRE             1
14                            ESF JOAO ALVES DA SILVA             1
15                         HOSPITAL REGIONAL DO JURUA             1
16                       POLO BASE DE CRUZEIRO DO SUL             1
17                        SAUDE DA FAMILIA RIBEIRINHA             1

In [310]:
#2. crie uma lista das colunas desse *DataFrame* com o atributo de *DataFrame* **.columns()**  
lista_colunas=paciente_menos_18.columns
lista_colunas

Index(['document_id', 'paciente_id', 'paciente_idade',
       'paciente_datanascimento', 'paciente_enumsexobiologico',
       'paciente_racacor_codigo', 'paciente_racacor_valor',
       'paciente_endereco_coibgemunicipio', 'paciente_endereco_copais',
       'paciente_endereco_nmmunicipio', 'paciente_endereco_nmpais',
       'paciente_endereco_uf', 'paciente_endereco_cep',
       'paciente_nacionalidade_enumnacionalidade', 'estabelecimento_valor',
       'estabelecimento_razaosocial', 'estalecimento_nofantasia',
       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome',
       'estabelecimento_uf', 'vacina_grupoatendimento_codigo',
       'vacina_grupoatendimento_nome', 'vacina_categoria_codigo',
       'vacina_categoria_nome', 'vacina_lote', 'vacina_fabricante_nome',
       'vacina_fabricante_referencia', 'vacina_dataaplicacao',
       'vacina_descricao_dose', 'vacina_codigo', 'vacina_nome',
       'sistema_origem', 'data_importacao_rnds', 'id_sistema_origem'],
      dtype='object')

In [312]:
#3. Nesse *DataFrame* faça uma contagem do campo ```vacina_categoria_nome```.
paciente_menos_18['vacina_categoria_nome'].value_counts()

Povos Indígenas                     33
Trabalhadores de Saúde               9
Povos e Comunidades Tradicionais     9
Comorbidades                         2
Faixa Etária                         1
Name: vacina_categoria_nome, dtype: int64

In [318]:
#4. a partir da lista de colunas, escolha somente aquelas que são referentes ao estabelecimento,faça uma lista com esses valores.
lista_estabelecimento=['estabelecimento_valor','estabelecimento_razaosocial', 'estalecimento_nofantasia',
                       'estabelecimento_municipio_codigo', 'estabelecimento_municipio_nome','estabelecimento_uf']

In [317]:
#5. usando o método *.loc*, selecione somente essas variáveis  

nova_lista_estab=paciente_menos_18.loc[:,lista_estabelecimento]
nova_lista_estab.head()

,estabelecimento_valor,estabelecimento_razaosocial,estalecimento_nofantasia,estabelecimento_municipio_codigo,estabelecimento_municipio_nome,estabelecimento_uf
1567,2001314,PREFEITURA MUNICIPAL DE EPITACIOLANDIA,ESF JOAO ALVES DA SILVA,120025,EPITACIOLANDIA,AC
6250,6917291,PREFEITURA MUNICIPAL DE RIO BRANCO,DEPARTAMENTO DE VIGILANCIA EPIDEMIOLOGICA E AM...,120040,RIO BRANCO,AC
9569,6159087,PREFEITURA MUNICIPAL DE CRUZEIRO DO SUL,SECRETARIA MUNICIPAL DE SAUDE DE CRUZEIRO DO SUL,120020,CRUZEIRO DO SUL,AC
11338,2000040,PREFEITURA MUNICIPAL DE FEIJO,CENTRO DE SAUDE DIAMANTINO MACEDO,120030,FEIJO,AC
15144,7625855,DISTRITO SANITARIO ESPECIAL INDIGENA ALTO RIO ...,POLO BASE DE MARECHAL THAUMATURGO,120035,MARECHAL THAUMATURGO,AC

In [319]:
#5. Aplique o método **.drop_duplicates** e crie uma lista com uma linha para cada estabelecimento,com os dados do estabelecimento  

nova_lista_estab=nova_lista_estab.drop_duplicates()

nova_lista_estab.shape

(18, 6)